$NetBSD: patch-Cargo.toml,v 1.1 2023/08/28 10:17:45 pin Exp $

Avoid libgit2 version mismatch.

--- Cargo.toml.orig	2023-08-25 16:44:13.000000000 +0000
+++ Cargo.toml
@@ -45,7 +45,7 @@ vsort = "0.1.0"
 
 [target."cfg(not(all(windows, target_arch = \"x86\", target_env = \"gnu\")))".dependencies]
 # if ssl feature is enabled compilation will fail on arm-unknown-linux-gnueabihf and i686-pc-windows-gnu
-git2 = { version = "0.16", optional = true, default-features = false }
+git2 = { version = "0.17", optional = true, default-features = false }
 
 [target.'cfg(unix)'.dependencies]
 users = "0.11.*"
