$NetBSD: patch-tests_Cargo.toml,v 1.4 2023/07/10 19:43:05 pin Exp $

Patch out the git source request for iai.

--- tests/Cargo.toml.orig	2023-06-30 14:21:57.000000000 +0000
+++ tests/Cargo.toml
@@ -10,7 +10,7 @@ publish = false
 typst = { path = ".." }
 typst-library = { path = "../library" }
 comemo = "0.3"
-iai = { git = "https://github.com/reknih/iai" }
+iai = "0.1.1"
 once_cell = "1"
 oxipng = "8.0.0"
 rayon = "1.7.0"
