$NetBSD: patch-Cargo.toml,v 1.1 2024/07/17 12:03:14 pin Exp $

Don't pull dev dependencies from git on a release.

--- Cargo.toml.orig	2024-06-25 13:18:24.962212271 +0000
+++ Cargo.toml
@@ -166,8 +166,8 @@ anstyle = "1.0.7"
 assert_fs = "1.1"
 predicates = "3.1"
 snapbox = "0.4.16"
-cargo-test-macro.git = "https://github.com/rust-lang/cargo"
-cargo-test-support.git = "https://github.com/rust-lang/cargo"
+cargo-test-macro = "0.1.0"
+cargo-test-support = "0.1.0"
 
 [profile.release]
 panic = "abort"
