$NetBSD: patch-Cargo.toml,v 1.1 2024/06/08 18:51:10 wiz Exp $

Depends on an unpublished crate. Can't use cargo.mk to fetch it.

--- Cargo.toml.orig	2024-06-08 12:11:01.018391496 +0000
+++ Cargo.toml
@@ -79,7 +79,7 @@ libc = { version = "0.2.153" }
 libcst = { version = "1.1.0", default-features = false }
 log = { version = "0.4.17" }
 lsp-server = { version = "0.7.6" }
-lsp-types = { git = "https://github.com/astral-sh/lsp-types.git", rev = "3512a9f", features = ["proposed"] }
+lsp-types = { path = "lsp-types-3512a9f33eadc5402cfab1b8f7340824c8ca1439", features = ["proposed"] }
 matchit = { version = "0.8.1" }
 memchr = { version = "2.7.1" }
 mimalloc = { version = "0.1.39" }
