$NetBSD: patch-frontend_jgenesis-gui_Cargo.toml,v 1.3 2024/10/08 14:39:41 wiz Exp $

xrandr is NOT Linux only, fix this non-sense.

--- frontend/jgenesis-gui/Cargo.toml.orig	2024-08-11 12:49:06.861702305 +0000
+++ frontend/jgenesis-gui/Cargo.toml
@@ -32,7 +32,7 @@ sdl2 = { workspace = true }
 time = { workspace = true, features = ["formatting", "local-offset"] }
 toml = { workspace = true }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
 xrandr = { workspace = true }
 
 [package.metadata.packager]
