$NetBSD: patch-frontend_jgenesis-renderer_Cargo.toml,v 1.1 2024/10/06 13:19:15 pin Exp $

Add glyphon path.

--- frontend/jgenesis-renderer/Cargo.toml.orig	2024-10-06 12:32:27.703566506 +0000
+++ frontend/jgenesis-renderer/Cargo.toml
@@ -11,7 +11,7 @@ jgenesis-common = { path = "../../jgenes
 
 bytemuck = { workspace = true }
 cfg-if = { workspace = true }
-glyphon = { workspace = true }
+glyphon = { path = "../../glyphon-47f4126f999753e14728c0862b822677f1b039e2" }
 log = { workspace = true }
 raw-window-handle = { workspace = true }
 serde = { workspace = true }
