$NetBSD: patch-Cargo.toml,v 1.4 2022/11/21 09:21:11 pin Exp $

Don't pull from git, patch vendor crate instead.

--- Cargo.toml.orig	2022-11-18 21:54:29.000000000 +0000
+++ Cargo.toml
@@ -24,7 +24,7 @@ log = "0.4.16"
 simplelog = "0.12.0"
 content_inspector = "0.2.4"
 crossterm = "0.25.0"
-syntect = {version = "5.0.0", git = "https://github.com/kyoheiu/syntect"}
+syntect = "5.0.0"
 serde_yaml = "0.9.14"
 zip = "0.6.3"
 tar = "0.4.38"
